---
es:
  admin:
    dashboard:
      keybase: Integración con keybase
    settings:
      enable_keybase:
        desc_html: Permite a tus usuarixs comprobar su identidad por medio de keybase
        title: Habilitar la integración con keybase
      outgoing_spoilers:
        desc_html: Cuando los hops federen, agrega esta etiqueta de contenido a los hops que no tengan. Es útil si tu servidor se especializa en contenido que otros servidores desearían tener con una advertencia de contenido. Los medios también se marcarán como sensibles.
        title: Advertencia de contenido para los hops salientes
      hide_followers_count:
        desc_html: No mostrar el conteo de seguidorxs en perfiles de usuarix
        title: Ocultar conteo de seguidorxs
      show_reblogs_in_public_timelines:
        desc_html: Mostrar rehops públicos en las línea de tiempo local y pública.
        title: Mostrar rehops en líneas de tiempo públicas
      show_replies_in_public_timelines:
        desc_html: Además de auto-respuestas públicas (hilos), mostrar respuestas públicas en las línea de tiempo local y pública.
        title: Mostrar respuestas en líneas de tiempo públicas
  generic:
    use_this: Usar
  settings:
    flavours: Ediciones
